config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  get 'admin_panel', to: 'admin_panel#index'

  #
  # Admin Section
  #
  post 'admin_create_video', to: "admin_panel#create_video"
  post 'admin_remove_video', to: "admin_panel#remove_video"
  post 'admin_create_user', to: "admin_panel#create_user"
  post 'admin_remove_user', to: "admin_panel#remove_user"
  post 'admin_add_admin_user', to: "admin_panel#create_admin_user"
  post 'seo_update_home', to: "admin_panel#seo_update_home"
  get 'admin_add_user', to: "admin_panel#create_video"
  get 'admin_workouts', to: "admin_panel#admin_workouts"
  get 'admin_users_mapping', to: "admin_panel#admin_users_mapping"
  get 'admin_user_connection', to: "admin_panel#admin_user_connection"
  get 'admin_add_videos', to: "admin_panel#admin_add_videos"
  # get 'admin_paypal_transactions', to: "admin_panel#admin_paypal_transactions"
  get 'admin_show_users', to: "admin_panel#admin_show_users"
  get 'admin_blogs', to: "admin_panel#admin_blogs"
  get 'seo_dynamic_data', to: "admin_panel#seo_dynamic_data"
  resources :free_videos

  resources :media
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :workout_sets
  get 'tutorials', to: "tutorials#index"
  #
  # DEVICE
  #
  devise_for :users,
             path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
             controllers: { sessions: 'users/sessions' }

  #
  # My Videos Section
  #
  get 'my_videos', to: "my_videos#index"
  get 'my_videos/:id', to: "my_videos#show"
  get 'contact_us', to: "contacts#index"

  #
  # PayPal Section
  #
  # get 'payment_details', to: "transaction#details"
  # get 'transactions/:id', to: "transaction#create_payment"
  # get 'payment_execute', to: "transaction#payment_execute"
  # get 'webhooks', to: "webhooks#index"
  # post 'webhooks', to: "webhooks#get_event"

  #
  # About
  #
  get 'about', to: "about#index"
end

app/models/free_video.rb
class FreeVideo < ApplicationRecord
end

app/controllers/free_videos_controller.rb
class FreeVideosController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?
  before_action :set_free_video, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /free_videos
  # GET /free_videos.json
  def index
    @free_videos = FreeVideo.all
  end

  # GET /free_videos/1
  # GET /free_videos/1.json
  def show
  end

  # GET /free_videos/new
  def new
    @free_video = FreeVideo.new
  end

  # GET /free_videos/1/edit
  def edit
  end

  # POST /free_videos
  # POST /free_videos.json
  def create
    video_params = free_video_params
    video_params[:url] = pars_youtube_link(video_params[:url])
    @free_video = FreeVideo.new(video_params)

    respond_to do |format|
      if @free_video.save
        format.html { redirect_to @free_video, notice: 'Free video was successfully created.' }
        format.json { render :show, status: :created, location: @free_video }
      else
        format.html { render :new }
        format.json { render json: @free_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /free_videos/1
  # PATCH/PUT /free_videos/1.json
  def update
    video_params = free_video_params
    video_params[:url] = pars_youtube_link(video_params[:url])
    respond_to do |format|
      if @free_video.update(video_params)
        format.html { redirect_to @free_video, notice: 'Free video was successfully updated.' }
        format.json { render :show, status: :ok, location: @free_video }
      else
        format.html { render :edit }
        format.json { render json: @free_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /free_videos/1
  # DELETE /free_videos/1.json
  def destroy
    @free_video.destroy
    respond_to do |format|
      format.html { redirect_to free_videos_url, notice: 'Free video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_free_video
    @free_video = FreeVideo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def free_video_params
    params.require(:free_video).permit(:title, :url, :description)
  end

  def pars_youtube_link(link)
    return link.scan(/src="(.*?)"/)[0][0] unless link == ''
    nil
  end
end

app/views/free_videos/_form.html.erb
<%= form_with(model: free_video, local: true) do |form| %>
  <% if free_video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(free_video.errors.count, "error") %> prohibited this free_video from being saved:</h2>

      <ul>
      <% free_video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :free_video_title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :free_video_url %>
    <small>This link needs to be an embed code from youtube. And should look like this:</small>
    <br>
    <small>&lt;iframe width=&quot;1228&quot; height=&quot;691&quot; src=&quot;https://www.youtube.com/embed/Oba-keArOSI&quot; frameborder=&quot;0&quot; allow=&quot;accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture&quot; allowfullscreen&gt;&lt;/iframe&gt;</small>
    <br>
    <small><b>Note:</b> When the page is saved it will show parsed short link without iframe, this is how it should be. Use iframe only for updating the form!</small>
    <br>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :free_video_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/free_videos/edit.html.erb
<%= stylesheet_link_tag "admin_panel" %>

<section>
  <div class="container mt-5 mb-5">
    <h1>Editing Free Video</h1>

    <%= render 'form', free_video: @free_video %>

    <%= link_to 'Show', @free_video %> |
    <%= link_to 'Back', free_videos_path %>
  </div>
</section>

app/views/free_videos/index.html.erb
<%= stylesheet_link_tag "admin_panel" %>

<section>
  <div class="container mt-5 mb-5">
    <h1>Free Videos</h1>

    <table>
      <thead>
      <tr>
        <th>Title</th>
        <th>Url</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @free_videos.each do |free_video| %>
        <tr>
          <td><%= free_video.title %></td>
          <td><%= free_video.url %></td>
          <td><%= free_video.description %></td>
          <td><%= link_to 'Show', free_video %></td>
          <td><%= link_to 'Edit', edit_free_video_path(free_video) %></td>
          <td><%= link_to 'Destroy', free_video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Free Video', new_free_video_path %>
    <br>
    <%= link_to 'Go Back', admin_panel_path %>
  </div>
</section>

app/views/free_videos/new.html.erb
<%= stylesheet_link_tag "admin_panel" %>

<section>
  <div class="container mt-5 mb-5">
    <h1>New Free Video</h1>

    <%= render 'form', free_video: @free_video %>

    <%= link_to 'Back', free_videos_path %>
  </div>
</section>

app/views/free_videos/show.html.erb
<%= stylesheet_link_tag "admin_panel" %>

<section>
  <div class="container mt-5 mb-5">
    <p>
      <strong>Title:</strong>
      <%= @free_video.title %>
    </p>

    <p>
      <strong>Url:</strong>
      <%= @free_video.url %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @free_video.description %>
    </p>

    <%= link_to 'Edit', edit_free_video_path(@free_video) %> |
    <%= link_to 'Back', free_videos_path %>
  </div>
</section>