config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  get 'admin_panel', to: 'admin_panel#index'

  #
  # Admin Section
  #
  post 'admin_create_video', to: "admin_panel#create_video"
  post 'admin_remove_video', to: "admin_panel#remove_video"
  post 'admin_create_user', to: "admin_panel#create_user"
  post 'admin_remove_user', to: "admin_panel#remove_user"
  post 'admin_add_admin_user', to: "admin_panel#create_admin_user"
  post 'seo_update_home', to: "admin_panel#seo_update_home"
  get 'admin_add_user', to: "admin_panel#create_video"
  get 'admin_workouts', to: "admin_panel#admin_workouts"
  get 'admin_users_mapping', to: "admin_panel#admin_users_mapping"
  get 'admin_user_connection', to: "admin_panel#admin_user_connection"
  get 'admin_add_videos', to: "admin_panel#admin_add_videos"
  # get 'admin_paypal_transactions', to: "admin_panel#admin_paypal_transactions"
  get 'admin_show_users', to: "admin_panel#admin_show_users"
  get 'admin_blogs', to: "admin_panel#admin_blogs"
  get 'seo_dynamic_data', to: "admin_panel#seo_dynamic_data"
  resources :free_videos

  resources :media
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :workout_sets
  get 'tutorials', to: "tutorials#index"
  #
  # DEVICE
  #
  devise_for :users,
             path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
             controllers: { sessions: 'users/sessions' }

  #
  # My Videos Section
  #
  get 'my_videos', to: "my_videos#index"
  get 'my_videos/:id', to: "my_videos#show"
  get 'contact_us', to: "contacts#index"

  #
  # PayPal Section
  #
  # get 'payment_details', to: "transaction#details"
  # get 'transactions/:id', to: "transaction#create_payment"
  # get 'payment_execute', to: "transaction#payment_execute"
  # get 'webhooks', to: "webhooks#index"
  # post 'webhooks', to: "webhooks#get_event"

  #
  # About
  #
  get 'about', to: "about#index"
end

app/views/aplication/_footer.html.erb
<div class="footer bg-darker">
  <!-- Footer -->
  <footer id="footer">
    <div class="container">
      <div class="row text-center text-xs-center text-sm-left text-md-left">
        <div class="col-xs-12 col-sm-4 col-md-4">
          <h5>Site Map</h5>
          <ul class="list-unstyled quick-links">
            <li><a href="<%= root_path %>"><i class="fa fa-angle-double-right"></i>Home</a></li>
            <li><a href="<%= workout_sets_path %>"><i class="fa fa-angle-double-right"></i>Workout Sets</a></li>
            <li><a href="<%= tutorials_path %>"><i class="fa fa-angle-double-right"></i>Tutorials</a></li>
            <li><a href="<%= blogs_path %>"><i class="fa fa-angle-double-right"></i>Blog</a></li>
            <li><a href="<%= contact_us_path %>"><i class="fa fa-angle-double-right"></i>Contact Me</a></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4">
          <h5>Personal Access</h5>
          <ul class="list-unstyled quick-links">
            <% if user_signed_in? && current_user.admin %>
              <li><a href="<%= admin_panel_path %>"><i class="fa fa-angle-double-right"></i>Admin Panel</a></li>
            <% end %>
            <% if user_signed_in? %>
              <li><a href="<%= my_videos_path %>"><i class="fa fa-angle-double-right"></i>My Videos</a></li>
            <% end %>
            <% if user_signed_in? %>
              <li><a href="<%= edit_user_registration_path %>"><i class="fa fa-angle-double-right"></i>My Profile</a></li>
            <% else %>
              <li><a href="<%= new_user_session_path %>"><i class="fa fa-angle-double-right"></i>Login</a></li>
              <li><a href="<%= new_user_registration_path %>"><i class="fa fa-angle-double-right"></i>Register</a></li>
            <% end %>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4">
          <h5>Latest Blogs</h5>
          <ul class="list-unstyled quick-links">
            <% Blog.order("created_at desc").limit(5).each do |blog| %>
              <li><a href="/blogs/<%= blog.id %>"><i class="fa fa-angle-double-right"></i><%= blog.title %></a></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
          <ul class="list-unstyled list-inline social text-center">
            <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fa fa-google-plus"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank"><i class="fa fa-envelope"></i></a></li>
          </ul>
        </div>
        </hr>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
          <p class="h6">&copy All right Reversed, All content belongs to Aermotion project and it's owner Mikhail Nazarev, <%= Date.today.year %></p>
          <p class="h6"><a class="ml-2" href="https://www.skrdev.com" target="_blank">Developed by Dmitrii Skrylev</a></p>
          <%= image_tag 'logo-title.png', class: "mt-3" %>
        </div>
        </hr>
      </div>
    </div>
  </footer>
  <!-- ./Footer -->
</div>

app/views/aplication/_navbar.html.erb
<div class="sticky-top toolbar transparent text-center">
  <div class="page-width">
    <div class="toolbar__content">

      <div class="toolbar__item toolbar-menu">
        <div class="my-2 my-md-0 mr-md-3">
          <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-darker" id="nav-holder">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "Workouts", workout_sets_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "Tutorials", tutorials_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "Blog", blogs_path, class: "nav-link effect-underline" %></li>
                <% if user_signed_in? %>
                  <li class="nav-item"><%= link_to "My Videos", my_videos_path, class: "nav-link" %></li>
                <% end %>
                <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "Contact", contact_us_path, class: "nav-link" %></li>
              </ul>
              <ul class="navbar-nav ml-auto">
                <i class="fa fa-user user-icon nav-link"></i>
                <% if user_signed_in? %>
                  <li class="nav-item"><%= link_to "My Profile", edit_user_registration_path, class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
                <% else %>
                  <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
                  <li class="nav-item"><%= link_to "Register", new_user_registration_path, class: "nav-link" %></li>
                <% end %>

                <% if user_signed_in? && current_user.admin %>
                  <li class="nav-item"><%= link_to "Admin Panel", admin_panel_path, class: "nav-link" %></li>
                <% end %>
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  window.onscroll = function() {scrollFunction()};

  function scrollFunction() {
    if (document.body.scrollTop > 50 || document.documentElement.scrollTop >= 80) {
      document.getElementById("nav-holder").style.fontSize = "20px";
      document.getElementById("nav-holder").style.padding = "0px";
      //parallax-window
    }
    else if (document.documentElement.scrollTop < 20) {
      document.getElementById("nav-holder").style.fontSize = "30px";
      document.getElementById("nav-holder").style.padding = "20px";
    }
  }
</script>

app/views/aplication/_show_blogs.html.erb
<% @blogs = Blog.order(id: :desc).limit(6) %>

<% if @blogs.exists? && @blogs.count >= 5 %>

  <div class="pb-5 d-none d-md-none d-lg-block">
    <div class="row blog-bg">
        <div class="col-8 p-0 blog-item">
          <a href="/blogs/<%= @blogs[0].id %>">
            <%= image_tag @blogs[0].main_image.variant(combine_options: { resize: '1300^', resize_to_fill: [1300, 905] }), class: "img-fluid", alt: "Responsive image"%>
            <div class="blog-bg">
              <h1 class="blog-title-text m-4"><%= @blogs[0].title %></h1>
            </div>
          </a>
        </div>
      <div class="col-4 p-0">
        <div class="blog-item">
          <a href="/blogs/<%= @blogs[1].id %>">
            <%= image_tag @blogs[1].main_image.variant(combine_options: { resize: '650^', resize_to_fill: [650, 463] }), class: "img-fluid", alt: "Responsive image" %>
            <div class="blog-bg">
              <h3 class="blog-title-text blog-text-l"><%= @blogs[1].title %></h3>
            </div>
          </a>
        </div>
        <div class="blog-item">
          <a href="/blogs/<%= @blogs[2].id %>">
            <%= image_tag @blogs[2].main_image.variant(combine_options: { resize: '650^', resize_to_fill: [650, 463] }), class: "img-fluid", alt: "Responsive image" %>
            <div class="blog-bg">
              <h3 class="blog-title-text blog-text-l"><%= @blogs[2].title %></h3>
            </div>
          </a>
        </div>
      </div>
    </div>
    <div class="row blog-bg">
      <div class="col-4 p-0 blog-item">
        <a href="/blogs/<%= @blogs[3].id %>">
          <%= image_tag @blogs[3].main_image.variant(combine_options: { resize: '650^', resize_to_fill: [650, 463] }), class: "img-fluid", alt: "Responsive image" %>
          <div class="blog-bg">
            <h3 class="blog-title-text blog-text-l"><%= @blogs[3].title %></h3>
          </div>
        </a>
      </div>
      <div class="col-4 p-0 blog-item">
        <a href="/blogs/<%= @blogs[4].id %>">
          <%= image_tag @blogs[4].main_image.variant(combine_options: { resize: '650^', resize_to_fill: [650, 463] }), class: "img-fluid", alt: "Responsive image" %>
          <div class="blog-bg">
            <h3 class="blog-title-text blog-text-l"><%= @blogs[4].title %></h3>
          </div>
        </a>
      </div>
      <div class="col-4 p-0 blog-item">
        <a href="/blogs/<%= @blogs[5].id %>">
          <%= image_tag @blogs[5].main_image.variant(combine_options: { resize: '650^', resize_to_fill: [650, 463] }), class: "img-fluid", alt: "Responsive image" %>
          <div class="blog-bg">
            <h3 class="blog-title-text blog-text-l"><%= @blogs[5].title %></h3>
          </div>
        </a>
      </div>
    </div>
  </div>

  <div class="pb-5 d-lg-none d-xl-none">
    <div class="col-12 p-0">
      <div class="blog-item">
        <a href="/blogs/<%= @blogs[0].id %>">
          <%= image_tag @blogs[0].main_image.variant(combine_options: { resize: '690^', resize_to_fill: [690, 463] }), class: "img-fluid", alt: "Responsive image" %>
          <div class="blog-bg">
            <h3 class="blog-title-text blog-text-l"><%= @blogs[0].title %></h3>
          </div>
        </a>
      </div>

      <div class="blog-item">
        <a href="/blogs/<%= @blogs[1].id %>">
          <%= image_tag @blogs[1].main_image.variant(combine_options: { resize: '690^', resize_to_fill: [690, 463] }), class: "img-fluid", alt: "Responsive image" %>
          <div class="blog-bg">
            <h3 class="blog-title-text blog-text-l"><%= @blogs[1].title %></h3>
          </div>
        </a>
      </div>

      <div class="blog-item">
        <a href="/blogs/<%= @blogs[2].id %>">
          <%= image_tag @blogs[2].main_image.variant(combine_options: { resize: '690^', resize_to_fill: [690, 463] }), class: "img-fluid", alt: "Responsive image" %>
          <div class="blog-bg">
            <h3 class="blog-title-text blog-text-l"><%= @blogs[2].title %></h3>
          </div>
        </a>
      </div>

      <div class="blog-item">
        <a href="/blogs/<%= @blogs[3].id %>">
          <%= image_tag @blogs[3].main_image.variant(combine_options: { resize: '690^', resize_to_fill: [690, 463] }), class: "img-fluid", alt: "Responsive image" %>
          <div class="blog-bg">
            <h3 class="blog-title-text blog-text-l"><%= @blogs[3].title %></h3>
          </div>
        </a>
      </div>

      <div class="blog-item">
        <a href="/blogs/<%= @blogs[4].id %>">
          <%= image_tag @blogs[4].main_image.variant(combine_options: { resize: '690^', resize_to_fill: [690, 463] }), class: "img-fluid", alt: "Responsive image" %>
          <div class="blog-bg">
            <h3 class="blog-title-text blog-text-l"><%= @blogs[4].title %></h3>
          </div>
        </a>
      </div>

      <div class="blog-item">
        <a href="/blogs/<%= @blogs[5].id %>">
          <%= image_tag @blogs[5].main_image.variant(combine_options: { resize: '690^', resize_to_fill: [690, 463] }), class: "img-fluid", alt: "Responsive image" %>
          <div class="blog-bg">
            <h3 class="blog-title-text blog-text-l"><%= @blogs[5].title %></h3>
          </div>
        </a>
      </div>
    </div>
  </div>
<% end %>

app/views/aplication/_show_free_videos.html.erb
<% @videos = FreeVideo.order('RANDOM()').take(4) %>

<div class="row justify-content-center">
  <% @videos.each do |v| %>
    <div class="embed-responsive embed-responsive-16by9 col-3">
      <iframe class="embed-responsive-item" src="<%= v.url %>" frameborder='0' allowfullscreen></iframe>
    </div>
  <% end %>
</div>

app/views/aplication/_show_tutorials.html.erb
<% @tutorials = WorkoutSet.all.includes(:type).where(type: Type.where(name:"Tutorial").take.id).order('RANDOM()').first(6) rescue nil %>

<style>
  a{
    text-decoration:none;
  }
  .section-title h4 {
    font-size: 14px;
    font-weight: 500;
    color: #777;
  }
  .section-title h2 {
    font-size: 32px;
    text-transform: capitalize;
    margin: 15px 0;
    display: inline-block;
    position: relative;
    font-weight: 700;
    padding-bottom: 15px;
    letter-spacing: 1px;
    text-transform: uppercase;
  }
  .section-title p {
    font-weight: 300;
    font-size: 14px;
  }
  .black-bg .section-title h2, .black-bg .section-title h4, .black-bg .section-title p {
    color:#fff
  }
  .section-title h2:before {
    position: absolute;
    content: "";
    width: 150px;
    height: 1px;
    background-color: #777;
    bottom: 0;
    left: 50%;
    margin-left: -75px;
  }
  .section-title h2:after {
    position: absolute;
    content: "";
    width: 80px;
    height: 3px;
    background-color: #4bb4e7;
    border: darkblue;
    bottom: -1px;
    left: 50%;
    margin-left: -40px;
  }
  .section-title {
    margin-bottom: 70px;
  }
  .single-price {
    text-align: center;
    padding: 10px;
    box-shadow: 0px 0px 2px rgba(0, 0, 0, 0.2);
  }
  .price-title h4 {
    font-size: 24px;
    text-transform: uppercase;
    font-weight: 600;
  }
  .price-tag {
    margin: 30px 0;
  }
  .price-tag {
    margin: 30px 0;
    background-color: #fafafa;
    color: #000;
    padding: 10px 0;
  }
  .center.price-tag {
    background-color: #4bb4e7;
    color:#fff
  }
  .price-tag h2 {
    font-size: 45px;
    font-weight: 600;
    font-family: poppins;
  }
  .price-tag h2 span {
    font-weight: 300;
    font-size: 16px;
    font-style: italic;
  }
  .price-item ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }
  .price-item ul li {
    font-size: 14px;
    padding: 5px 0;
    border-bottom: 1px dashed #eee;
    margin: 5px 0;
  }
  .price-item ul li:last-child {
    border-bottom: 0;
  }
  .single-price a {
    margin-top: 15px;
  }
  a.box-btn {
    background-color: #333333;
    padding: 5px 20px;
    display: inline-block;
    color: #fff;
    text-transform: capitalize;
    border-radius: 3px;
    font-size: 15px;
    transition: .3s;
  }
  a.box-btn:hover, a.border-btn:hover {
    background-color: #4bb4e7;
  }
</style>

<div class="pricing-area container mt-3 mb-3" id="pricing">
  <div class="">
    <div class="row">
      <div class="col-xl-8 mx-auto text-center">
        <div class="section-title">
          <h4>cheap prices</h4>
          <h2>Tutorials</h2>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting.</p>
        </div>
      </div>
    </div>
    <div class="row">


    <% unless @tutorials.nil? %>
      <% @tutorials.each do |t| %>
        <div class="col-xl-2">
          <div class="single-price">
            <div class="price-title">
              <h4>tutorial</h4>
            </div>
            <div class="price-tag">
              <h2>$<%= t.price %></h2>
            </div>
            <div class="price-item">
              <ul>
                <li><%= t.title %></li>
                <li>Videos included: <%= t.media.count %></li>
                <li>Video Time Count</li>
              </ul>
            </div>
            <a href="/workout_sets/<%= t.id %>" class="box-btn">purchase now</a>
          </div>
        </div>
      <% end %>
    <% end %>





    </div>
  </div>
</div>

app/views/aplication/_show_workouts.html.erb
<% @workouts = WorkoutSet.includes(:type).where(type: Type.where(name:"Set").take.id).order('RANDOM()').first(6) rescue nil %>

<% unless @workouts.nil? %>
  <% unless @workouts[0].nil? %>
    <div class="card mb-3" style="width: 22rem;">
      <div class="card-body">
        <h5 class="card-title"><%= image_tag 'dumbbell.png', style: "width: 20px; margin-bottom: 3px;" %> <%= @workouts[0].title %></h5>
        <p class="card-text"><%= @workouts[0].description.first(150) unless @workouts[0].description.is_a?(NilClass) %>...</p>
        <a href="/workout_sets/<%= @workouts[0].id %>" class="btn btn-secondary">Read More</a>
      </div>
    </div>
  <% end %>

  <% unless @workouts[1].nil? %>
    <div class="card mb-3" style="width: 22rem;">
      <div class="card-body">
        <h5 class="card-title"><%= image_tag 'dumbbell.png', style: "width: 20px; margin-bottom: 3px;" %> <%= @workouts[1].title %></h5>
        <p class="card-text"><%= @workouts[1].description.first(150) unless @workouts[1].description.is_a?(NilClass) %>...</p>
        <a href="/workout_sets/<%= @workouts[1].id %>" class="btn btn-secondary">Read More</a>
      </div>
    </div>
  <% end %>

  <% unless @workouts[2].nil? %>
    <div class="card mb-3" style="width: 22rem;">
      <div class="card-body">
        <h5 class="card-title"><%= image_tag 'dumbbell.png', style: "width: 20px; margin-bottom: 3px;" %> <%= @workouts[2].title %></h5>
        <p class="card-text"><%= @workouts[2].description.first(150) unless @workouts[2].description.is_a?(NilClass) %>...</p>
        <a href="/workout_sets/<%= @workouts[2].id %>" class="btn btn-secondary">Read More</a>
      </div>
    </div>
  <% end %>

  <% unless @workouts[3].nil? %>
    <div class="card mb-3" style="width: 22rem;">
      <div class="card-body">
        <h5 class="card-title"><%= image_tag 'dumbbell.png', style: "width: 20px; margin-bottom: 3px;" %> <%= @workouts[3].title %></h5>
        <p class="card-text"><%= @workouts[3].description.first(150) unless @workouts[3].description.is_a?(NilClass) %>...</p>
        <a href="/workout_sets/<%= @workouts[3].id %>" class="btn btn-secondary">Read More</a>
      </div>
    </div>
  <% end %>

  <% unless @workouts[4].nil? %>
    <div class="card mb-3" style="width: 22rem;">
      <div class="card-body">
        <h5 class="card-title"><%= image_tag 'dumbbell.png', style: "width: 20px; margin-bottom: 3px;" %> <%= @workouts[4].title %></h5>
        <p class="card-text"><%= @workouts[4].description.first(150) unless @workouts[4].description.is_a?(NilClass) %>...</p>
        <a href="/workout_sets/<%= @workouts[4].id %>" class="btn btn-secondary">Read More</a>
      </div>
    </div>
  <% end %>

  <% unless @workouts[5].nil? %>
    <div class="card mb-3" style="width: 22rem;">
      <div class="card-body">
        <h5 class="card-title"><%= image_tag 'dumbbell.png', style: "width: 20px; margin-bottom: 3px;" %> <%= @workouts[5].title %></h5>
        <p class="card-text"><%= @workouts[5].description.first(150) unless @workouts[5].description.is_a?(NilClass) %>...</p>
        <a href="/workout_sets/<%= @workouts[5].id %>" class="btn btn-secondary">Read More</a>
      </div>
    </div>
  <% end %>
<% end %>