config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  get 'admin_panel', to: 'admin_panel#index'

  #
  # Admin Section
  #
  post 'admin_create_video', to: "admin_panel#create_video"
  post 'admin_remove_video', to: "admin_panel#remove_video"
  post 'admin_create_user', to: "admin_panel#create_user"
  post 'admin_remove_user', to: "admin_panel#remove_user"
  post 'admin_add_admin_user', to: "admin_panel#create_admin_user"
  post 'seo_update_home', to: "admin_panel#seo_update_home"
  get 'admin_add_user', to: "admin_panel#create_video"
  get 'admin_workouts', to: "admin_panel#admin_workouts"
  get 'admin_users_mapping', to: "admin_panel#admin_users_mapping"
  get 'admin_user_connection', to: "admin_panel#admin_user_connection"
  get 'admin_add_videos', to: "admin_panel#admin_add_videos"
  # get 'admin_paypal_transactions', to: "admin_panel#admin_paypal_transactions"
  get 'admin_show_users', to: "admin_panel#admin_show_users"
  get 'admin_blogs', to: "admin_panel#admin_blogs"
  get 'seo_dynamic_data', to: "admin_panel#seo_dynamic_data"
  resources :free_videos

  resources :media
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :workout_sets
  get 'tutorials', to: "tutorials#index"
  #
  # DEVICE
  #
  devise_for :users,
             path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
             controllers: { sessions: 'users/sessions' }

  #
  # My Videos Section
  #
  get 'my_videos', to: "my_videos#index"
  get 'my_videos/:id', to: "my_videos#show"
  get 'contact_us', to: "contacts#index"

  #
  # PayPal Section
  #
  # get 'payment_details', to: "transaction#details"
  # get 'transactions/:id', to: "transaction#create_payment"
  # get 'payment_execute', to: "transaction#payment_execute"
  # get 'webhooks', to: "webhooks#index"
  # post 'webhooks', to: "webhooks#get_event"

  #
  # About
  #
  get 'about', to: "about#index"
end

app/controllers/admin_panel_controller.rb
class AdminPanelController < ApplicationController

  before_action :authenticate_user!
  before_action :is_admin?

  def index
  end

  def admin_show_users
    @users = User.order(:id).page(params[:page]).per(10)
  end

  def admin_workouts
    @workouts = WorkoutSet.order(:id).page(params[:page]).per(10)
  end

  def admin_users_mapping
    @users = User.order(:id).page(params[:page]).per(5)
  end

  def admin_user_connection
    @users = User.order(:id).page(params[:page]).per(10)
  end

  def admin_add_videos
    @videos = Medium.order(:id).page(params[:page]).per(10)
  end

  # def admin_paypal_transactions
  #   @transactions = PayPalTransaction.order("id DESC").page(params[:page]).per(10)
  # end

  def new_video
    @workouts = WorkoutSet.all
  end

  def admin_blogs
    @blogs = Blog.order(:id).page(params[:page]).per(10)
  end

  def create_video
    param_container = format_params
    message = "Link was successfully created."
    param_container.medium_id.each do |m|
      next if m == ""
      unless MediaWorkoutSet.where(medium_id: m, workout_set_id: param_container.workout_id) == []
        message += "\nExcept Video: '#{Medium.find(m).title}' and Workout Set: '#{WorkoutSet.find(param_container.workout_id).title}' already linked."
        next
      end
      link = MediaWorkoutSet.new(medium_id: m, workout_set_id: param_container.workout_id)
      if link.save
      else
        flash[:notice] = "Not saved: #{link.errors}"
      end
    end
    redirect_to admin_panel_path, notice: message
  end

  def remove_video
    param_container = format_params
    message = "Link was successfully removed."
    param_container.medium_id.each do |m|
      next if m == ""
      if MediaWorkoutSet.where(medium_id: m, workout_set_id: param_container.workout_id) == []
        message += "\nExcept Video: '#{Medium.find(m).title}' and Workout Set: '#{WorkoutSet.find(param_container.workout_id).title}' already removed."
        next
      end
      link = MediaWorkoutSet.where(medium_id: m, workout_set_id: param_container.workout_id)
      link.delete_all
    end
    redirect_to admin_panel_path, notice: message
  end

  def create_user
    param_container = format_params_user

    message = "Link was successfully created."
    param_container.workout_id.each do |w|
      next if w == ""
      unless UsersWorkoutSet.where(user_id: param_container.user_id, workout_set_id: w) == []
        message += "\nExcept User: '#{User.find(param_container.user_id).email}' and Workout Set: '#{WorkoutSet.find(w).title}' already linked."
        next
      end
      link = UsersWorkoutSet.new(user_id: param_container.user_id, workout_set_id: w)
      if link.save
      else
        flash[:notice] = "Not saved: #{link.errors}"
      end
    end
    redirect_to admin_panel_path, notice: message
  end

  def remove_user
    param_container = format_params_user

    message = "Link was successfully removed."
    param_container.workout_id.each do |w|
      next if w == ""
      if UsersWorkoutSet.where(user_id: param_container.user_id, workout_set_id: w) == []
        message += "\nExcept User: '#{User.find(param_container.user_id).email}' and Workout Set: '#{WorkoutSet.find(w).title}' already removed."
        next
      end
      link = UsersWorkoutSet.where(user_id: param_container.user_id, workout_set_id: w)
      link.delete_all
    end
    redirect_to admin_panel_path, notice: message
  end

  def create_admin_user
    user = User.new(
        email: format_params_admin_user.email,
        password: format_params_admin_user.encrypted_password
    )
    if user.save
      redirect_to admin_user_connection_path, notice: "Admin user successfully created"
    else
      redirect_to admin_user_connection_path, notice: user.errors
    end
  end

  def seo_dynamic_data
    @site_config = SiteConfiguration.all
  end

  def seo_update_home
    success_flags = []
    error_flags = []
    settings = home_page_dynamic

    if home_page_dynamic[:home_page_introduction_video_url].include?('iframe')
      settings[:home_page_introduction_video_url] = pars_youtube_link(home_page_dynamic[:home_page_introduction_video_url])
    end


    settings.each do |key, value|
      updating_key = SiteConfiguration.where(key: key).first
      unless updating_key.value == value
        if updating_key.update(value: value)
          success_flags << "Key #{key} was successfully updated and set to Value: #{value}"
        else
          error_flags << "Could not update Key #{key}. Possibly missing key in the configuration defaults check SiteConfiguration table"
        end
      end
    end

    SiteConfiguration.where(key: 'home_page_image').first.main_image.attach(settings[:home_page_image])

    respond_to do |format|
      if error_flags.length <= 0
        format.html { redirect_to seo_dynamic_data_path, notice: "#{ success_flags.length < 1 ? 'There was nothing to update!' : 'Settings updated successfully: ' + success_flags.join("\n") }" }
        format.json { render seo_dynamic_data_path, status: :created}
      else
        format.html { redirect_to seo_dynamic_data_path, notice: error_flags.inspect }
        format.json { render json: seo_dynamic_data_path.inspect , status: :unprocessable_entity }
      end
    end
  end

  private
  def link_set_params
    params.require(:link_sets).permit(
        :workout_link,
        :user_link,
        :admin_email,
        :admin_password,
        workout_link_list:[],
        video_link: [])
  end

  def format_params
    OpenStruct.new(
        medium_id: link_set_params[:video_link],
        workout_id: link_set_params[:workout_link]
    )
  end

  def format_params_user
    OpenStruct.new(
        user_id: link_set_params[:user_link],
        workout_id: link_set_params[:workout_link_list]
    )
  end

  def format_params_admin_user
    OpenStruct.new(
        email: link_set_params[:admin_email],
        encrypted_password: link_set_params[:admin_password]
    )
  end

  def is_admin?
    redirect_to root_path unless current_user.admin
  end

  def home_page_dynamic
    params.require(:home_page).permit(
        :home_page_title,
        :home_page_blue_part,
        :home_page_sub_title,
        :home_page_sub_title_two,
        :home_page_introduction_video_title,
        :home_page_introduction_video_sub_title,
        :home_page_introduction_video_url,
        :home_page_workouts_title,
        :home_page_workouts_sub_title,
        :home_page_tutorials_title,
        :home_page_tutorials_sub_title,
        :home_page_blogs_title,
        :home_page_blogs_sub_title,
        :home_page_contact_block,
        :home_page_html_title,
        :home_page_html_keys,
        :home_page_image
    )
  end

  def pars_youtube_link(link)
    return link.scan(/src="(.*?)"/)[0][0] unless link == ''
    nil
  end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/views/admin_panel/_moda_video.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Select Video to Add</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <%= form_with scope: "link_sets", url: admin_create_video_path do |form| %>
          <div class="field">
            Workout_id = <%= workout.id %>
            <%= form.collection_select(:video_link, Medium.all, :id, :title, {}, multiple: true  )%>
            <%= form.hidden_field(:workout_link, value: workout.id) %>
          </div>

          </div>
          <div class="modal-footer">
            <%= form.submit %>
            <button type="button" class="btn btn-primary">Cancel</button>
        <% end %>
        </div>
        </div>
  </div>
</div>

app/views/admin_panel/_modal_remove_user.html.erb
<!-- Modal -->
<div class="modal fade" id="removeWorkoutUser" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Select Video to Remove</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with scope: "link_sets", url: admin_remove_user_path do |form| %>
          <div class="field">
            Selected workoutsets below will be added to User:
            <%= form.collection_select(:workout_link_list, WorkoutSet.all, :id, :title, {}, multiple: true, class: "form-control")%>
            <%= form.hidden_field(:user_link, id: "workout-modal") %>
          </div>

          </div>
          <div class="modal-footer">
            <%= form.submit "Remove", class: "btn btn-danger" %>
            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
        <% end %>
        </div>
        </div>
  </div>
</div>

app/views/admin_panel/_modal_remove_video.html.erb
<!-- Modal -->
<div class="modal fade" id="removeWorkoutVideo" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Select Video to Remove</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with scope: "link_sets", url: admin_remove_video_path do |form| %>
          <div class="field">
            Selected videos below will be removed from Workout Set:
            <%= form.collection_select(:video_link, Medium.all, :id, :title, {}, multiple: true, class: "form-control")%>
            <%= form.hidden_field(:workout_link, id: "workout-modal") %>
          </div>

          </div>
          <div class="modal-footer">
            <%= form.submit "Remove", class: "btn btn-danger" %>
            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
        <% end %>
        </div>
        </div>
  </div>
</div>

app/views/admin_panel/_modal_user.html.erb
<!-- Modal -->
<div class="modal fade" id="addUserModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">Select Workout Sets</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with scope: "link_sets", url: admin_create_user_path do |form| %>
          <div class="field">
            Selected workoutsets below will be added to User:
            <%= form.collection_select(:workout_link_list, WorkoutSet.all, :id, :title, {}, multiple: true, class: "form-control")%>
            <%= form.hidden_field(:user_link, id: "workout-modal") %>
          </div>

          </div>
          <div class="modal-footer">
            <%= form.submit "Add", class: "btn btn-success" %>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
        <% end %>
        </div>
        </div>
  </div>
</div>

app/views/admin_panel/_search.html.erb
<%= form_tag(edit_user_registration_path, method: "get") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Enter search term" %>
  <%= submit_tag "Search" %>
<% end %>

app/views/admin_panel/admin_add_videos.html.erb
<%= stylesheet_link_tag "admin_panel" %>

<section>
  <div class="container mt-5 mb-5">
    <small>Total: <%= @videos.count %> video/s</small>
    <%= paginate @videos %>
    <table>
      <thead>
      <tr class="admin-head">
        <th class="text-center">Title</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <% @videos.each do |v| %>
        <tr class="admin-row">
          <td><a href="/media/<%= v.id %>"><%= v.title %></a></td>
          <td><%= link_to 'Edit', edit_medium_path(v) %></td>
          <td><%= link_to 'Destroy', v, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>
    <%= paginate @videos %>
    <%= link_to "Back", admin_panel_path %>
  </div>
</section>

app/views/admin_panel/admin_blogs.html.erb
<%= stylesheet_link_tag "admin_panel" %>

<section>
  <div class="container mt-5 mb-5">
    <%= paginate @blogs %>
    <table>
      <thead>
      <tr class="admin-head">
        <th class="text-center">Entry ID</th>
        <th class="text-center">Title</th>
        <th class="text-center">Actions</th>
      </tr>
      </thead>

      <% @blogs.each do |b| %>
        <tr class="admin-row">
          <td><%= b.id %></td>
          <td><%= b.title %></td>
          <td>
            <%= link_to 'Show', blog_path(b) %>
            <%= link_to 'Edit', edit_blog_path(b) %>
            <%= link_to 'Destroy', b, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </table>
    <%= paginate @blogs %>
    <%= link_to 'Add New', new_blog_path %>
    <hr>
    <%= link_to "Back", admin_panel_path %>
  </div>
</section>

app/views/admin_panel/admin_paypal_transactions.html.erb
<%#= stylesheet_link_tag "admin_panel" %>

<!--<section>-->
<!--  <div class="container mt-5 mb-5">-->
    <%#= paginate @transactions %>
<!--    <table>-->
<!--      <thead>-->
<!--      <tr class="admin-head">-->
<!--        <th class="text-center">Entry ID</th>-->
<!--        <th class="text-center">Transaction ID</th>-->
<!--        <th class="text-center">User ID Local</th>-->
<!--        <th class="text-center">User Email Local</th>-->
<!--        <th class="text-center">Payment Method</th>-->
<!--        <th class="text-center">Payer ID PayPal</th>-->
<!--        <th class="text-center">Item</th>-->
<!--        <th class="text-center">Price</th>-->
<!--        <th class="text-center">Currency</th>-->
<!--        <th class="text-center">Quantity</th>-->
<!--        <th class="text-center">Tax</th>-->
<!--        <th class="text-center">Total</th>-->
<!--        <th class="text-center">Time Created PayPal</th>-->
<!--        <th class="text-center">Status</th>-->
<!--        <th class="text-center">Error</th>-->
<!--        <th class="text-center">Created At</th>-->
<!--        <th class="text-center">Updated At</th>-->
<!--        <th colspan="3"></th>-->
<!--      </tr>-->
<!--      </thead>-->

      <%# @transactions.each do |t| %>
<!--        <tr class="admin-row">-->
<!--          <td><%#= t.id %></td>-->
<!--          <td><%#= t.transaction_id %></td>-->
<!--          <td><%#= t.local_user_id %></td>-->
<!--          <td><%#= t.local_user_email %></td>-->
<!--          <td><%#= t.method %></td>-->
<!--          <td><%#= t.payer_id %></td>-->
<!--          <td><%#= t.item %></td>-->
<!--          <td><%#= t.price %></td>-->
<!--          <td><%#= t.currency %></td>-->
<!--          <td><%#= t.quantity %></td>-->
<!--          <td><%#= t.tax %></td>-->
<!--          <td><%#= t.total %></td>-->
<!--          <td><%#= t.paypal_created_time %></td>-->
<!--          <td><%#= t.status %></td>-->
<!--          <td><%#= t.error %></td>-->
<!--          <td><%#= t.created_at %></td>-->
<!--          <td><%#= t.updated_at %></td>-->
<!--        </tr>-->
      <%# end %>
<!--    </table>-->
    <%#= paginate @transactions %>
    <%#= link_to "Back", admin_panel_path %>
<!--  </div>-->
<!--</section>-->

app/views/admin_panel/admin_show_users.html.erb
<%= stylesheet_link_tag "admin_panel" %>

<section>
  <div class="container mt-5">
    <%= paginate @users %>
    <table>
      <thead>
      <tr class="admin-head">
        <th class="text-center">ID</th>
        <th class="text-center">Email Address</th>
        <th class="text-center">Reset Password Sent At</th>
        <th class="text-center">Remember Created At</th>
        <th class="text-center">Sign in Count</th>
        <th class="text-center">Current Sign in At</th>
        <th class="text-center">Last Sign in At</th>
        <th class="text-center">Current Sign in IP</th>
        <th class="text-center">Last Sign in IP</th>
        <th class="text-center">Created At</th>
        <th class="text-center">Updated At</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <% @users.each do |u| %>
        <tr class="admin-row">
          <td><%= u.id %></td>
          <td><%= u.email %></td>
          <td><%= u.reset_password_sent_at %></td>
          <td><%= u.remember_created_at %></td>
          <td><%= u.sign_in_count %></td>
          <td><%= u.current_sign_in_at %></td>
          <td><%= u.last_sign_in_at %></td>
          <td><%= u.current_sign_in_ip %></td>
          <td><%= u.last_sign_in_ip %></td>
          <td><%= u.created_at %></td>
          <td><%= u.updated_at %></td>
        </tr>
      <% end %>
    </table>
    <%= paginate @users %>
    <%= link_to "Back", admin_panel_path %>
  </div>
</section>

app/views/admin_panel/admin_user_connection.html.erb
<%= javascript_include_tag 'admin_panel' %>
<%= stylesheet_link_tag "admin_panel" %>

<section>
  <div class="container mt-5 mb-5">
    <%= paginate @users %>
    <table>
      <thead>
      <tr class="admin-head">
        <th class="text-center">ID</th>
        <th class="text-center">Email</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <% @users.each do |user| %>
        <tr class="admin-row">
          <td class="text-center"><%= user.id %></td>
          <td class="text-center"><%= user.email %></td>
          <td class="text-center">

            <% user.workout_sets.each do |w| %>
              <div>
                <a href="/media/<%= w.id %>"><%= w.title %></a>
              </div>
            <% end %>

          </td>
          <td>
            <button type="button" class="btn btn-success" onclick="showUserPopup('<%= user.id %>')" data-toggle="modal" >
              +
            </button>
            <button type="button" class="btn btn-danger" onclick="showRemoveUser('<%= user.id %>')" data-toggle="modal" >
              -
            </button>
          </td>
        </tr>
      <% end %>

    </table>
    <%= paginate @users %>
    <small>In order to add regular user - use standard registration form</small>
    <br>
    <button type="button" class="btn btn-success" onclick="showAddAdmin()" data-toggle="modal" >
      Create Admin
    </button>
    <%= link_to 'Back', admin_panel_path %>
  </div>

  <%= render 'modal_user' %>
  <%= render 'modal_remove_user' %>
  <%= render 'modal_add_admin_user' %>
</section>

app/views/admin_panel/admin_workouts.html.erb
<%= javascript_include_tag 'admin_panel' %>
<%= stylesheet_link_tag "admin_panel" %>

<section>
  <div class="container mt-5 mb-5">
    <%= paginate @workouts %>
    <table>
      <thead>
      <tr class="admin-head">
        <th class="text-center">ID</th>
        <th class="text-center">Name</th>
        <th class="text-center">Price</th>
        <th class="text-center">Type</th>
        <th class="text-center">Actions</th>
        <th class="text-center">Videos</th>
        <th class="text-center">Video Actions</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <% @workouts.each do |workout| %>
        <tr class="admin-row">
          <td class="text-center"><%= workout.id %></td>
          <td class="text-center"><%= workout.title %></td>
          <td class="text-center"><%= workout.price %></td>
          <td class="text-center"><%= workout.type.name %></td>
          <td class="text-center">
            <%= link_to 'Show', workout_set_path(workout) %>
            <%= link_to 'Edit', edit_workout_set_path(workout) %>
            <%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
          <td class="text-center">

            <% workout.media.each do |m| %>
              <div>
                <a href="/media/<%= m.id %>"><%= m.title %></a>
              </div>
            <% end %>

          </td>
          <td>
            <button type="button" class="btn btn-success" onclick="showPopup('<%= workout.id %>')" data-toggle="modal" >
              +
            </button>
            <button type="button" class="btn btn-danger" onclick="showRemove('<%= workout.id %>')" data-toggle="modal" >
              -
            </button>
          </td>
        </tr>
      <% end %>
    </table>
    <%= paginate @workouts %>
    <%= link_to 'Back', admin_panel_path %>
  </div>

  <%= render 'modal_video' %>
  <%= render 'modal_remove_video' %>
</section>

app/views/admin_panel/index.html.erb
<%= stylesheet_link_tag "admin_panel" %>

<section>
  <div class="container pt-3">
    <div class="header-title">
      <h1 class="">Admin Panel</h1>
    </div>
    <hr>

    <ul>
      <h3 class="mt-3">Main Info:</h3>
      <li><%= link_to 'Users Mapping', admin_users_mapping_path %></li>
      <li><%= link_to 'Users', admin_show_users_path %></li>

      <h3 class="mt-3">Workout Sets:</h3>
      <li><%= link_to 'Add/Remove Videos to Workout Sets', admin_workouts_path %></li>
      <li><%= link_to "Add new Workout/Tutorial", new_workout_set_path %></li>
      <li><%= link_to 'Add/Remove Users to Workout Sets', admin_user_connection_path %></li>

      <h3 class="mt-3">Video Content:</h3>
      <li><%= link_to 'View/Remove/Update Videos', admin_add_videos_path %></li>
      <li><%= link_to "Upload New Video", new_medium_path %></li>

      <h3 class="mt-3">Payments Invoices:</h3>
      <div class="text-secondary">This function is disabled</div>
<!--      <li><%#= link_to 'PayPal Transactions', admin_paypal_transactions_path %></li>-->

      <h3 class="mt-3">My Blog:</h3>
      <li><%= link_to 'Add New Blog', new_blog_path %></li>
      <li><%= link_to 'View/Edit/Delete Blogs', admin_blogs_path %></li>
      <li><%= link_to 'User View', blogs_path %></li>

      <h3 class="mt-3">YouTube Free Content:</h3>
      <li><%= link_to 'Add YouTube Video', new_free_video_path %></li>
      <li><%= link_to 'View/Remove/Update YouTube Videos', free_videos_path %></li>

      <h3 class="mt-3">SEO and Site Data:</h3>
      <li><%= link_to 'Update Your Web Site SEO and Dynamic data', seo_dynamic_data_path %></li>
    </ul>
  </div>
</section>

app/views/admin_panel/new_video.html.erb
<section>
  <h1>Add video to set</h1>
  <%= render 'add_video_form' %>
</section>